// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHD1enqQ0IYC3b9WC_FLV9bSZ01yoQByI',
    appId: '1:786885723364:web:6e36858e50d56cacb458f1',
    messagingSenderId: '786885723364',
    projectId: 'sudoku-battle-cluj',
    authDomain: 'sudoku-battle-cluj.firebaseapp.com',
    storageBucket: 'sudoku-battle-cluj.firebasestorage.app',
    measurementId: 'G-LPH5X07QG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRIMH76vQlBkqwPfJV_GMx7EI4b2OdeyM',
    appId: '1:786885723364:android:154f95432b8d1a17b458f1',
    messagingSenderId: '786885723364',
    projectId: 'sudoku-battle-cluj',
    storageBucket: 'sudoku-battle-cluj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3rTjbobgDM9QUefBPEH8mhevWfe33A0Y',
    appId: '1:786885723364:ios:540a26f67a4913b1b458f1',
    messagingSenderId: '786885723364',
    projectId: 'sudoku-battle-cluj',
    storageBucket: 'sudoku-battle-cluj.firebasestorage.app',
    iosBundleId: 'com.example.sudokuBattle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3rTjbobgDM9QUefBPEH8mhevWfe33A0Y',
    appId: '1:786885723364:ios:540a26f67a4913b1b458f1',
    messagingSenderId: '786885723364',
    projectId: 'sudoku-battle-cluj',
    storageBucket: 'sudoku-battle-cluj.firebasestorage.app',
    iosBundleId: 'com.example.sudokuBattle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHD1enqQ0IYC3b9WC_FLV9bSZ01yoQByI',
    appId: '1:786885723364:web:17041870b35fec22b458f1',
    messagingSenderId: '786885723364',
    projectId: 'sudoku-battle-cluj',
    authDomain: 'sudoku-battle-cluj.firebaseapp.com',
    storageBucket: 'sudoku-battle-cluj.firebasestorage.app',
    measurementId: 'G-QQ1YZXWNZC',
  );

}